### ISSUE TITLE
add group argument

### ISSUE THREAD

**Issue by arielfuentes** [cran/leaflet.minicharts#4]
Can you add a group variable for the addFlow to be added to addLayersControl?, check this question. 
https://stackoverflow.com/questions/59565891/leaflet-minichars-group-argument

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by mayeulk** [comment]
Note: the active repository is: https://github.com/rte-antares-rpackage/leaflet.minicharts
